In [1]:
import polars as pl

In [7]:
df = pl.read_csv('./PAES_performance_seed12.csv')
df

shape: (8, 2)
┌────────┬──────────┐
│ prompt ┆ qwk      │
│ ---    ┆ ---      │
│ i64    ┆ f64      │
╞════════╪══════════╡
│ 1      ┆ 0.771362 │
│ 2      ┆ 0.535935 │
│ 3      ┆ 0.500562 │
│ 4      ┆ 0.567202 │
│ 5      ┆ 0.726061 │
│ 6      ┆ 0.56175  │
│ 7      ┆ 0.713473 │
│ 8      ┆ 0.548791 │
└────────┴──────────┘

In [8]:
df.mean()

shape: (1, 2)
┌────────┬──────────┐
│ prompt ┆ qwk      │
│ ---    ┆ ---      │
│ f64    ┆ f64      │
╞════════╪══════════╡
│ 4.5    ┆ 0.615642 │
└────────┴──────────┘