In [2]:
import json
import polars as pl

In [10]:
results = {}
for d_size in [10, 20, 30, 40, 50, 100, 200, 500]:
    qwks = []
    for i in range(1, 9):
        with open(f'devonly_{i}_{d_size}.json', 'r') as f:
            data = json.load(f)
            qwk = data['eval_qwk']
        qwks.append(qwk)
    results[str(d_size)] = qwks
df = pl.DataFrame(results)

In [11]:
df

shape: (8, 8)
┌──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┐
│ 10       ┆ 20       ┆ 30       ┆ 40       ┆ 50       ┆ 100      ┆ 200      ┆ 500      │
│ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ f64      ┆ f64      ┆ f64      ┆ f64      ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
╞══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╡
│ 0.162063 ┆ 0.260031 ┆ 0.223765 ┆ 0.455621 ┆ 0.498374 ┆ 0.544586 ┆ 0.715865 ┆ 0.795114 │
│ 0.003479 ┆ 0.338486 ┆ 0.15662  ┆ 0.453182 ┆ 0.338508 ┆ 0.46371  ┆ 0.610769 ┆ 0.660467 │
│ 0.104926 ┆ 0.3578   ┆ 0.190751 ┆ 0.429541 ┆ 0.460916 ┆ 0.602823 ┆ 0.626806 ┆ 0.639401 │
│ 0.319703 ┆ 0.435976 ┆ 0.494578 ┆ 0.652283 ┆ 0.646885 ┆ 0.705608 ┆ 0.752102 ┆ 0.789169 │
│ 0.31266  ┆ 0.391323 ┆ 0.436269 ┆ 0.581714 ┆ 0.583179 ┆ 0.716119 ┆ 0.759647 ┆ 0.792599 │
│ 0.346832 ┆ 0.398301 ┆ 0.350704 ┆ 0.510266 ┆ 0.543173 ┆ 0.697722 ┆ 0.749244 ┆ 0.773588 │
│ 0.373399 ┆ 0.309137 ┆ 0.284677 ┆ 0.563234 ┆ 0.567183 ┆ 0.740271 ┆ 0.732575 ┆ 0.816349 │
│ 0.196755 ┆ 0.241308 ┆ 0.230562 ┆ 0.364601 ┆ 0.593244 ┆ 0.541813 ┆ 0.622166 ┆ 0.687537 │
└──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┘

In [12]:
df.mean()

shape: (1, 8)
┌──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┐
│ 10       ┆ 20       ┆ 30       ┆ 40       ┆ 50       ┆ 100      ┆ 200      ┆ 500      │
│ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ f64      ┆ f64      ┆ f64      ┆ f64      ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
╞══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╡
│ 0.227477 ┆ 0.341545 ┆ 0.295991 ┆ 0.501305 ┆ 0.528933 ┆ 0.626582 ┆ 0.696147 ┆ 0.744278 │
└──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┘